In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import plotly.express as px

file1_path = "/content/drive/MyDrive/Fall 2025 CUNY Recommendation File Import 1_File1.csv"
file2_path = "/content/drive/MyDrive/Fall 2025 CUNY Recommendation File Import 1_File2.csv"

df1 = pd.read_csv(file1_path, encoding="latin1")
df2 = pd.read_csv(file2_path, encoding="latin1")

In [ ]:
df1.head()

,Evaluation Code,Recommendation,College GPA Consolidated - GPA,College Last Attended - Name,HS Average - GPA,HS Average ENGL - GPA,HS Average Lang - GPA,HS Average Math - GPA,HS Average Sci - GPA,HS Average Socs - GPA,HS Last Attended - Name
0,XFERREG,ADMIT,3.24,Kingsborough Community College,,,,,,,El Cajon Valley HS
1,XFERREG,ADMIT,2.1,Kingsborough Community College,74.95,,,,,,William E. Grady Vo-Tec HS
2,XFERREG,ADMIT,2.27,Borough of Manhattan Community College,,,,,,,GED / TASC / HiSET - NY
3,XFERREG,ADMIT,2.66,Eastern Gateway CC,72.64,,,,,,Franklin K Lane HS
4,XFERREG,ADMIT,2.46,Borough of Manhattan Community College,,,,,,,GED / TASC / HiSET - NY

In [ ]:
df2.head()

,Evaluation Code,Recommendation,College GPA Consolidated - GPA,College Last Attended - Name,HS Average - GPA,HS Average ENGL - GPA,HS Average Lang - GPA,HS Average Math - GPA,HS Average Sci - GPA,HS Average Socs - GPA,HS Last Attended - Name
0,FRSHREG,ADMIT,,,94.62,92,93.67,96.33,95.17,93.4,M.S. 260 Clinton School Writers & Artists
1,FRSHREG,ADMIT,,,91.81,92.67,NaN,92.17,89.00,93.8,Marble Hill HS for International Studies
2,FRSHREG,ADMIT,,,89.62,92,83.67,87.30,89.50,88.17,Brooklyn Technical HS
3,FRSHREG,ADMIT,,,87.81,88.17,87,91.33,91.17,86.67,Bronx Academy of Letters
4,FRSHREG,ADMIT,,,93.00,92.17,94,88.35,91.25,90.33,Brooklyn Prospect Charter School

In [ ]:
df = pd.concat([df1, df2], ignore_index=True)

In [ ]:
df.head()

,Evaluation Code,Recommendation,College GPA Consolidated - GPA,College Last Attended - Name,HS Average - GPA,HS Average ENGL - GPA,HS Average Lang - GPA,HS Average Math - GPA,HS Average Sci - GPA,HS Average Socs - GPA,HS Last Attended - Name
0,XFERREG,ADMIT,3.24,Kingsborough Community College,,,,,,,El Cajon Valley HS
1,XFERREG,ADMIT,2.1,Kingsborough Community College,74.95,,,,,,William E. Grady Vo-Tec HS
2,XFERREG,ADMIT,2.27,Borough of Manhattan Community College,,,,,,,GED / TASC / HiSET - NY
3,XFERREG,ADMIT,2.66,Eastern Gateway CC,72.64,,,,,,Franklin K Lane HS
4,XFERREG,ADMIT,2.46,Borough of Manhattan Community College,,,,,,,GED / TASC / HiSET - NY

In [ ]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(' ', '_')
      .str.replace('-', '_')
      .str.replace('/', '_')
      .str.replace(r'_+', '_', regex=True)
      .str.strip('_')
)
# Clean column names

In [ ]:
df.head()

,evaluation_code,recommendation,college_gpa_consolidated_gpa,college_last_attended_name,hs_average_gpa,hs_average_engl_gpa,hs_average_lang_gpa,hs_average_math_gpa,hs_average_sci_gpa,hs_average_socs_gpa,hs_last_attended_name
0,XFERREG,ADMIT,3.24,Kingsborough Community College,,,,,,,El Cajon Valley HS
1,XFERREG,ADMIT,2.1,Kingsborough Community College,74.95,,,,,,William E. Grady Vo-Tec HS
2,XFERREG,ADMIT,2.27,Borough of Manhattan Community College,,,,,,,GED / TASC / HiSET - NY
3,XFERREG,ADMIT,2.66,Eastern Gateway CC,72.64,,,,,,Franklin K Lane HS
4,XFERREG,ADMIT,2.46,Borough of Manhattan Community College,,,,,,,GED / TASC / HiSET - NY

In [ ]:
gpa_cols = [
    "college_gpa_consolidated_gpa",
    "hs_average_gpa",
    "hs_average_engl_gpa",
    "hs_average_lang_gpa",
    "hs_average_math_gpa",
    "hs_average_sci_gpa",
    "hs_average_socs_gpa"
]

# Convert to numeric
for col in gpa_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [ ]:
df_hs = df[df["evaluation_code"] == "FRSHREG"].copy()

In [ ]:
cols_to_drop = [
    "college_gpa_consolidated_gpa",
    "college_last_attended_name",
    "hs_average_lang_gpa"
]

df_hs = df_hs.drop(columns=cols_to_drop, errors="ignore")

# Drop rows with missing values
df_hs_clean = df_hs.dropna().copy()

In [ ]:
df_hs_clean.head()

,evaluation_code,recommendation,hs_average_gpa,hs_average_engl_gpa,hs_average_math_gpa,hs_average_sci_gpa,hs_average_socs_gpa,hs_last_attended_name
11,FRSHREG,ADMIT,97.30,96.67,97.00,96.00,95.67,New Explorations Science Technology Math
12,FRSHREG,ADMIT,96.93,96.00,97.25,95.33,96.17,Young Womens Leadership School Queens
13,FRSHREG,ADMIT,97.56,98.17,96.30,96.83,97.38,Brooklyn Technical HS
14,FRSHREG,ADMIT,97.87,99.00,97.25,97.36,96.50,Bronx HS of Science
34,FRSHREG,ADMIT,93.49,92.25,92.71,94.50,92.00,Urban Action Academy

In [ ]:
from google.colab import files

# Save to CSV
df_hs_clean.to_csv("df_hs_clean.csv", index=False)

# Download file
files.download("df_hs_clean.csv")

In [ ]:
color_map = {
    "ADMIT": "#003f5c",
    "DENY": "#ffa600"
}

fig = px.histogram(
    df_hs_clean,
    x="hs_average_gpa",
    color="recommendation",
    nbins=30,
    barmode="overlay",
    opacity=0.65,
    color_discrete_map=color_map,
    title="GPA Distribution: Admitted vs Denied Students"
)

fig.update_layout(
    xaxis_title="High school average GPA",
    yaxis_title="Number of applicants",
    legend_title="Recommendation",
    template="simple_white"
)

fig.show()

In [ ]:
# Group by high school and count applicants
hs_counts = (
    df_hs_clean
    .groupby("hs_last_attended_name", as_index=False)
    .size()
    .rename(columns={"size": "applicant_count"})
    .sort_values("applicant_count", ascending=False)
    .head(10)
)

# Bar chart for top 10 schools
fig = px.bar(
    hs_counts,
    x="hs_last_attended_name",
    y="applicant_count",
    color="hs_last_attended_name",      # each bar different color
    title="Top 10 High Schools by Number of Applicants",
    text="applicant_count",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    xaxis_title="High school",
    yaxis_title="Number of applicants",
    template="simple_white",
    showlegend=False
)

fig.update_traces(
    textposition="outside"
)

fig.update_xaxes(tickangle=45)

fig.show()

In [ ]:
# Count total applicants per HS
total = (
    df_hs_clean
    .groupby("hs_last_attended_name", as_index=False)
    .size()
    .rename(columns={"size": "total_applicants"})
)

# Count admitted applicants per HS
admits = (
    df_hs_clean[df_hs_clean["recommendation"] == "ADMIT"]
    .groupby("hs_last_attended_name", as_index=False)
    .size()
    .rename(columns={"size": "admitted"})
)

# Merge and compute admit rate
merged = total.merge(admits, on="hs_last_attended_name", how="left")
merged["admitted"] = merged["admitted"].fillna(0)
merged["admit_rate"] = merged["admitted"] / merged["total_applicants"]

# Select top 10 by total applicants
top10 = merged.sort_values("total_applicants", ascending=False).head(10)

# Sort by admit rate
top10 = top10.sort_values("admit_rate", ascending=False)

# Bar chart sorted by admit rate
fig = px.bar(
    top10,
    x="hs_last_attended_name",
    y="admit_rate",
    color="hs_last_attended_name",   # each bar different color
    text=(top10["admit_rate"] * 100).round(1).astype(str) + "%",
    title="Admit Rate by High School (Top 10 by Applicant Count)",
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig.update_layout(
    xaxis_title="High school",
    yaxis_title="Admit rate",
    template="simple_white",
    showlegend=False
)

fig.update_xaxes(tickangle=45)

fig.update_traces(textposition="outside")

fig.show()

In [ ]:
# Create GPA bands
bins = [70, 75, 80, 85, 90, 95, 100]
labels = ["70-75", "75-80", "80-85", "85-90", "90-95", "95-100"]

df_hs_clean["gpa_band"] = pd.cut(
    df_hs_clean["hs_average_gpa"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

# Compute admit rate for each band
band_stats = (
    df_hs_clean.groupby("gpa_band")
    .agg(
        total_applicants=("hs_average_gpa", "count"),
        admitted=("recommendation", lambda x: (x == "ADMIT").sum())
    )
    .reset_index()
)

band_stats["admit_rate"] = band_stats["admitted"] / band_stats["total_applicants"]

# Line plot
fig = px.line(
    band_stats,
    x="gpa_band",
    y="admit_rate",
    markers=True,
    title="Admit Rate by GPA Band"
)

fig.update_traces(
    line_color="#1b9e77",   # teal
    marker=dict(size=10, color="#1b9e77")
)

fig.update_layout(
    xaxis_title="GPA Band",
    yaxis_title="Admit Rate",
    template="simple_white"
)

fig.show()

/tmp/ipython-input-642826559.py:17: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
# Define GPA bands
bins = [70, 75, 80, 85, 90, 95, 100]
labels = ["70-75", "75-80", "80-85", "85-90", "90-95", "95-100"]

def plot_subject_gpa_band(df, column, title):
    # Create band column
    band_col = column + "_band"

    df[band_col] = pd.cut(
        df[column],
        bins=bins,
        labels=labels,
        include_lowest=True
    )

    # Compute admit stats
    stats = (
        df.groupby(band_col)
        .agg(
            total_applicants=(column, "count"),
            admitted=("recommendation", lambda x: (x == "ADMIT").sum())
        )
        .reset_index()
    )

    stats["admit_rate"] = stats["admitted"] / stats["total_applicants"]

    # Plot line chart
    fig = px.line(
        stats,
        x=band_col,
        y="admit_rate",
        markers=True,
        title=title
    )

    fig.update_traces(
        line_color="#1b9e77",
        marker=dict(size=10, color="#1b9e77")
    )

    fig.update_layout(
        xaxis_title="GPA Band",
        yaxis_title="Admit Rate",
        template="simple_white"
    )

    fig.show()

In [ ]:
plot_subject_gpa_band(
    df_hs_clean,
    "hs_average_engl_gpa",
    "Admit Rate by English GPA Band"
)

/tmp/ipython-input-4280670604.py:21: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
plot_subject_gpa_band(
    df_hs_clean,
    "hs_average_math_gpa",
    "Admit Rate by Math GPA Band"
)

/tmp/ipython-input-4280670604.py:21: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
plot_subject_gpa_band(
    df_hs_clean,
    "hs_average_sci_gpa",
    "Admit Rate by Science GPA Band"
)

/tmp/ipython-input-4280670604.py:21: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
plot_subject_gpa_band(
    df_hs_clean,
    "hs_average_socs_gpa",
    "Admit Rate by Social Studies GPA Band"
)

/tmp/ipython-input-4280670604.py:21: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:

color_map = {
    "ADMIT": "#1b9e77",
    "DENY": "#4d4d4d"
}

def avg_other_subjects(df, exclude_col):
    subjects = [
        "hs_average_engl_gpa",
        "hs_average_math_gpa",
        "hs_average_sci_gpa",
        "hs_average_socs_gpa"
    ]
    return df[[s for s in subjects if s != exclude_col]].mean(axis=1)

In [ ]:
def plot_subject_flipped(df, subject_col, subject_name):
    d = df.copy()
    d["avg_other"] = avg_other_subjects(d, subject_col)

    fig = px.scatter(
        d,
        x="avg_other",
        y=subject_col,
        color="recommendation",
        color_discrete_map=color_map,
        opacity=0.6,
        title=f"{subject_name} vs Average of Other Subjects (Flipped to Show Outliers on Top-Right)"
    )

    fig.update_layout(
        xaxis_title="Average of Other Subjects",
        yaxis_title=f"{subject_name} GPA",
        template="simple_white",
        legend_title="Recommendation",
        yaxis=dict(autorange="reversed")  # Flip y-axis to show outliers top-right
    )

    fig.show()

In [ ]:
df_deny = df_hs_clean[df_hs_clean["recommendation"] == "DENY"]
plot_subject_flipped(df_deny, "hs_average_math_gpa", "Math")

In [ ]:
plot_subject_flipped(df_deny, "hs_average_math_gpa", "Math")
plot_subject_flipped(df_deny, "hs_average_engl_gpa", "English")
plot_subject_flipped(df_deny, "hs_average_sci_gpa", "Science")
plot_subject_flipped(df_deny, "hs_average_socs_gpa", "Social Studies")

In [ ]:
# Filter for DENY students
df_deny = df_hs_clean[df_hs_clean["recommendation"] == "DENY"].copy()


color_above = "#1b9e77"
color_below = "red"

# Subject cutoff values
subject_cutoffs = {
    "hs_average_engl_gpa": 85,
    "hs_average_math_gpa": 85,
    "hs_average_sci_gpa": 85,
    "hs_average_socs_gpa": 85
}

def avg_other_subjects(df, exclude_col):
    subjects = [
        "hs_average_engl_gpa",
        "hs_average_math_gpa",
        "hs_average_sci_gpa",
        "hs_average_socs_gpa"
    ]
    return df[[s for s in subjects if s != exclude_col]].mean(axis=1)

In [ ]:
def plot_subject_with_cutoff(df, subject_col, subject_name):
    d = df.copy()
    d["avg_other"] = avg_other_subjects(d, subject_col)

    cutoff = subject_cutoffs[subject_col]

    # Create status for legend
    d["status"] = d[subject_col].apply(
        lambda v: "Below cutoff" if v < cutoff else "Above cutoff"
    )

    fig = px.scatter(
        d,
        x="avg_other",
        y=subject_col,
        color="status",
        color_discrete_map={
            "Below cutoff": color_below,
            "Above cutoff": color_above
        },
        opacity=0.6,
        hover_data=[
            "hs_last_attended_name",
            "hs_average_engl_gpa",
            "hs_average_math_gpa",
            "hs_average_sci_gpa",
            "hs_average_socs_gpa"
        ],
        title=f"(DENY Only) {subject_name} vs Average of Other Subjects"
    )

    fig.update_layout(
        xaxis_title="Average GPA of Other Subjects",
        yaxis_title=f"{subject_name} GPA",
        template="simple_white",
        legend_title="Subject status",
        yaxis=dict(autorange="reversed")    # Flip y-axis
    )

    # Add cutoff line
    fig.add_hline(y=cutoff, line_dash="dash", line_color="black")

    fig.show()

In [ ]:
plot_subject_with_cutoff(df_deny, "hs_average_math_gpa", "Math")

In [ ]:
plot_subject_with_cutoff(df_deny, "hs_average_engl_gpa", "English")
plot_subject_with_cutoff(df_deny, "hs_average_sci_gpa", "Science")
plot_subject_with_cutoff(df_deny, "hs_average_socs_gpa", "Social Studies")

In [ ]:
df_hs_clean.recommendation.value_counts()

recommendation
ADMIT    5920
DENY     3087
Name: count, dtype: int64

In [ ]:
df_hs_clean.to_csv("fall_2025_hs_file_combined.csv", index=False)