In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Mount Google Drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,evaluation_code,recommendation,hs_average_gpa,hs_average_engl_gpa,hs_average_math_gpa,hs_average_sci_gpa,hs_average_socs_gpa,hs_last_attended_name,gpa_band,hs_average_engl_gpa_band,hs_average_math_gpa_band,hs_average_sci_gpa_band,hs_average_socs_gpa_band
0,FRSHREG,ADMIT,97.30,96.67,97.00,96.00,95.67,New Explorations Science Technology Math,95-100,95-100,95-100,95-100,95-100
1,FRSHREG,ADMIT,96.93,96.00,97.25,95.33,96.17,Young Womens Leadership School Queens,95-100,95-100,95-100,95-100,95-100
2,FRSHREG,ADMIT,97.56,98.17,96.30,96.83,97.38,Brooklyn Technical HS,95-100,95-100,95-100,95-100,95-100
3,FRSHREG,ADMIT,97.87,99.00,97.25,97.36,96.50,Bronx HS of Science,95-100,95-100,95-100,95-100,95-100
4,FRSHREG,ADMIT,93.49,92.25,92.71,94.50,92.00,Urban Action Academy,90-95,90-95,90-95,90-95,90-95

In [ ]:
# Read the CSV data
file_path = "/content/drive/MyDrive/df_hs_clean.csv"

df_hs_clean = pd.read_csv(file_path)

df_hs_clean.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_hs_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9007 entries, 0 to 9006
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   evaluation_code           9007 non-null   object
 1   recommendation            9007 non-null   object
 2   hs_average_gpa            9007 non-null   float64
 3   hs_average_engl_gpa       9007 non-null   float64
 4   hs_average_math_gpa       9007 non-null   float64
 5   hs_average_sci_gpa        9007 non-null   float64
 6   hs_average_socs_gpa       9007 non-null   float64
 7   hs_last_attended_name     9007 non-null   object
 8   gpa_band                  8198 non-null   object
 9   hs_average_engl_gpa_band  8098 non-null   object
 10  hs_average_math_gpa_band  7414 non-null   object
 11  hs_average_sci_gpa_band   7814 non-null   object
 12  hs_average_socs_gpa_band  8009 non-null   object
dtypes: float64(5), object(8)
memory usage: 914.9+ KB

In [ ]:
band_cols = [
    "gpa_band",
    "hs_average_engl_gpa_band",
    "hs_average_math_gpa_band",
    "hs_average_sci_gpa_band",
    "hs_average_socs_gpa_band",
]

df_hs_clean = df_hs_clean.drop(columns=band_cols)

df_hs_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9007 entries, 0 to 9006
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   evaluation_code        9007 non-null   object
 1   recommendation         9007 non-null   object
 2   hs_average_gpa         9007 non-null   float64
 3   hs_average_engl_gpa    9007 non-null   float64
 4   hs_average_math_gpa    9007 non-null   float64
 5   hs_average_sci_gpa     9007 non-null   float64
 6   hs_average_socs_gpa    9007 non-null   float64
 7   hs_last_attended_name  9007 non-null   object
 8   gender                 9007 non-null   object
dtypes: float64(5), object(4)
memory usage: 633.4+ KB

In [ ]:
df_hs_clean.gender.value_counts()

gender
Women      4950
Men        3666
Unknown     272
Other       119
Name: count, dtype: int64

In [ ]:
df_hs_clean.ethnicity_ipeds.value_counts()

ethnicity_ipeds
Hispanic/Latino                              2339
Asian                                        2335
White                                        1985
Black or African American                    1774
Nonresident alien                             309
Two or more races                             253
American Indian or Alaskan Native               8
Native Hawaiian or Other Pacific Islander       4
Name: count, dtype: int64

In [ ]:
major_map = {
    "Undeclared 99999 Major or Program": "Undeclared Major",
    "BUSADM BBA 30604 Business Administration": "Business Administration BBA",
    "BIO BS 01984 Biology": "Biology BS",
    "COMPSC BS 01991 Computer Science": "Computer Science BS",
    "PSYCH BA 02096 Psychology": "Psychology BA",
    "FINC BBA 37634 Finance BBA": "Finance BBA",
    "PSYCH BS 02098 Psychology": "Psychology BS",
    "ART BA 02015 Art": "Art BA",
    "FILM BA 02023 Film": "Film BA",
    "BIO BA 01985 Biology": "Biology BA",
    "HNTRSC BS 85301 Health and Nutrition Sciences": "Health and Nutrition Sciences BS",
    "BMF BS 85067 Business Management": "Business Management BS",
    "PEDEXER BS 32345 Exercise Science": "Exercise Science BS",
    "POLSCI BA 02109 Political Science": "Political Science BA",
    "ACCTFIN BS 42470 Public Accounting and Finance BS": "Public Accounting and Finance BS",
    "PABMF BS 35423 Public Accounting and Business Management": "Public Accounting and Business Management BS",
    "COMM BA 31603 Communication": "Communication BA",
    "SLPASHS BA 85189 Communication Sciences and Disorders": "Communication Sciences and Disorders BA",
    "PHYS BS 02070 Physics": "Physics BS",
    "PHIL BA 02057 Philosophy": "Philosophy BA",
    "HIST BA 02106 History": "History BA",
    "ECO BA 01889 Economics": "Economics BA",
    "ENGL BA 02043 English": "English BA",
    "INFOSCI BS 32153 Information Systems": "Information Systems BS",
    "CWRTG BFA 87220 Creative Writing": "Creative Writing BFA",
    "ANTHRO BA 02102 Anthropology": "Anthropology BA",
    "BRDCST BS 83638 Journalism and Media Studies": "Journalism and Media Studies BS",
    "ACCNT BBA 92277 General Accounting": "Accounting BBA",
    "MATH BA 02064 Mathematics": "Mathematics BA",
    "CHEM BS 02084 Chemistry": "Chemistry BS",
    "FINMATH BS 34144 Financial Mathematics": "Financial Mathematics BS",
    "THEA BA 76210 Theater": "Theater BA",
    "MATH BS 02065 Mathematics": "Mathematics BS",
    "ART BFA 82460 Art": "Art BFA",
    "PHYS BA 02071 Physics": "Physics BA",
    "GEO BA 02090 Earth and Environmental Sciences": "Earth and Environmental Sciences BA",
    "EES BS 02092 Earth and Environmental Science": "Earth and Environmental Science BS",
    "HNTRSC BA 85300 Health and Nutrition Sciences": "Health and Nutrition Sciences BA",
    "MPERF BMUS 02018 Music Performance": "Music Performance BMUS",
    "TVR BA 76212 Television and Radio": "Television and Radio BA",
    "MULTI BS 31604 Multimedia Computing": "Multimedia Computing BS",
    "PEDTCHR BS 26746 Physical Education Teacher": "Physical Education Teacher BS",
    "MHC THE BA 60089 MHC Theatre": "Theatre BA MHC",
    "SPECED BA 81375 Professional Communication": "Professional Communication BA",
    "CMPMTH BS 02067 Computational Mathematics": "Computational Mathematics BS",
    "MHC MUS BA 60072 MHC Music": "Music BA MHC",
    "MHC HNS BS 60062 MHC Health and Nutrition Sciences": "Health and Nutrition Sciences BS MHC",
    "MUSED BMUS 26815 Music Teacher All Grades": "Music Teacher BMUS All Grades",
    "LINGX BA 02051 Linguistics": "Linguistics BA",
    "MUS BA 02021 Music": "Music BA",
    "ACTMATH BS 34143 Actuarial Mathematics": "Actuarial Mathematics BS",
    "ENVST BA 21627 Environmental Studies": "Environmental Studies BA",
    "SOC BA 02111 Sociology": "Sociology BA",
    "CET BA 26829 Childhood Ed Teacher Grades 1 to 6": "Childhood Education BA Grades 1–6",
    "MHCFCNC BBA 37635 MHC Finance BBA": "Finance BBA MHC",
}


df_hs_clean["major_clean"] = df_hs_clean["program"].map(major_map).fillna(df_hs_clean["program"])
df_hs_clean[["program", "major_clean"]].head()

                                    program                  major_clean
0                          ART BA 02015 Art                       Art BA
1                      BIO BS 01984 Biology                   Biology BS
2                          ART BA 02015 Art                       Art BA
3  BUSADM BBA 30604 Business Administration  Business Administration BBA
4         Undeclared 99999 Major or Program             Undeclared Major

In [ ]:
df_hs_clean.major_clean.value_counts()

major_clean
Undeclared Major                                2721
Business Administration BBA                     1165
Biology BS                                       854
Computer Science BS                              769
Psychology BA                                    421
Finance BBA                                      377
Psychology BS                                    263
Art BA                                           222
Film BA                                          218
Biology BA                                       216
Health and Nutrition Sciences BS                 203
Business Management BS                           184
Exercise Science BS                              154
Political Science BA                             140
Public Accounting and Finance BS                 126
Public Accounting and Business Management BS     116
Communication BA                                  67
Communication Sciences and Disorders BA           64
Physics BS                                        63
Philosophy BA                                     62
History BA                                        50
Economics BA                                      49
English BA                                        37
Information Systems BS                            36
Creative Writing BFA                              35
Anthropology BA                                   33
Journalism and Media Studies BS                   29
Accounting BBA                                    28
Mathematics BA                                    21
Chemistry BS                                      21
Financial Mathematics BS                          20
Theater BA                                        18
Mathematics BS                                    18
Art BFA                                           17
Physics BA                                        17
Earth and Environmental Sciences BA               17
Earth and Environmental Science BS                16
Health and Nutrition Sciences BA                  16
Music Performance BMUS                            13
Television and Radio BA                           13
Multimedia Computing BS                           13
Physical Education Teacher BS                     10
Theatre BA MHC                                     9
Professional Communication BA                      8
Computational Mathematics BS                       8
Music BA MHC                                       7
Health and Nutrition Sciences BS MHC               7
Music Teacher BMUS All Grades                      7
Linguistics BA                                     6
Music BA                                           5
Actuarial Mathematics BS                           5
Environmental Studies BA                           4
Sociology BA                                       4
Childhood Education BA Grades 1–6                  4
Finance BBA MHC                                    1
Name: count, dtype: int64

In [ ]:
df_hs_clean.columns

Index(['evaluation_code', 'recommendation', 'hs_average_gpa',
       'hs_average_engl_gpa', 'hs_average_math_gpa', 'hs_average_sci_gpa',
       'hs_average_socs_gpa', 'hs_last_attended_name', 'gender',
       'ethnicity_ipeds', 'program', 'major_clean'],
      dtype='object')

In [ ]:
df_hs_clean.head()

,evaluation_code,recommendation,hs_average_gpa,hs_average_engl_gpa,hs_average_math_gpa,hs_average_sci_gpa,hs_average_socs_gpa,hs_last_attended_name,gender,ethnicity_ipeds,program,major_clean
0,FRSHREG,ADMIT,97.30,96.67,97.00,96.00,95.67,New Explorations Science Technology Math,Men,White,ART BA 02015 Art,Art BA
1,FRSHREG,ADMIT,96.93,96.00,97.25,95.33,96.17,Young Womens Leadership School Queens,Women,Asian,BIO BS 01984 Biology,Biology BS
2,FRSHREG,ADMIT,97.56,98.17,96.30,96.83,97.38,Brooklyn Technical HS,Women,Hispanic/Latino,ART BA 02015 Art,Art BA
3,FRSHREG,ADMIT,97.87,99.00,97.25,97.36,96.50,Bronx HS of Science,Women,Two or more races,BUSADM BBA 30604 Business Administration,Business Administration BBA
4,FRSHREG,ADMIT,93.49,92.25,92.71,94.50,92.00,Urban Action Academy,Men,Hispanic/Latino,Undeclared 99999 Major or Program,Undeclared Major

In [ ]:
final_cols = [
    "evaluation_code",
    "recommendation",
    "gender",
    "ethnicity_ipeds",
    "hs_last_attended_name",
    "hs_average_gpa",
    "hs_average_engl_gpa",
    "hs_average_math_gpa",
    "hs_average_sci_gpa",
    "hs_average_socs_gpa",
    "major_clean"
]

df_hs_clean = df_hs_clean.drop(columns=["program"])
df_hs_clean = df_hs_clean[final_cols]
df_hs_clean.head()

,evaluation_code,recommendation,gender,ethnicity_ipeds,hs_last_attended_name,hs_average_gpa,hs_average_engl_gpa,hs_average_math_gpa,hs_average_sci_gpa,hs_average_socs_gpa,major_clean
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67,Art BA
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17,Biology BS
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38,Art BA
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50,Business Administration BBA
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00,Undeclared Major

In [ ]:
df_hs_clean = df_hs_clean.rename(columns={
    "major_clean": "intended_major",
    "ethnicity_ipeds": "ethnicity",
    "hs_average_gpa": "overall_gpa",
    "hs_average_engl_gpa": "english_gpa",
    "hs_average_math_gpa": "math_gpa",
    "hs_average_sci_gpa": "science_gpa",
    "hs_average_socs_gpa": "social_studies_gpa"
})

df_hs_clean.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa,intended_major
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67,Art BA
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17,Biology BS
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38,Art BA
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50,Business Administration BBA
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00,Undeclared Major

In [ ]:
core_cols = [
    "evaluation_code",
    "recommendation",
    "hs_last_attended_name",
    "overall_gpa",
    "english_gpa",
    "math_gpa",
    "science_gpa",
    "social_studies_gpa"
]

df_hs_academic = df_hs_clean[core_cols].copy()
df_hs_demographic = df_hs_clean.drop(columns=core_cols).copy()

df_hs_academic.head(), df_hs_demographic.head()

(  evaluation_code recommendation                     hs_last_attended_name  \
 0         FRSHREG          ADMIT  New Explorations Science Technology Math
 1         FRSHREG          ADMIT     Young Womens Leadership School Queens
 2         FRSHREG          ADMIT                     Brooklyn Technical HS
 3         FRSHREG          ADMIT                       Bronx HS of Science
 4         FRSHREG          ADMIT                      Urban Action Academy

    overall_gpa  english_gpa  math_gpa  science_gpa  social_studies_gpa
 0        97.30        96.67     97.00        96.00               95.67
 1        96.93        96.00     97.25        95.33               96.17
 2        97.56        98.17     96.30        96.83               97.38
 3        97.87        99.00     97.25        97.36               96.50
 4        93.49        92.25     92.71        94.50               92.00  ,
   gender          ethnicity               intended_major
 0    Men              White                       Art BA
 1  Women              Asian                   Biology BS
 2  Women    Hispanic/Latino                       Art BA
 3  Women  Two or more races  Business Administration BBA
 4    Men    Hispanic/Latino             Undeclared Major)

In [ ]:
df_hs_clean.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa,intended_major
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67,Art BA
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17,Biology BS
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38,Art BA
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50,Business Administration BBA
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00,Undeclared Major

In [ ]:
df = df_hs_clean.copy()

In [ ]:
df.recommendation.value_counts()

recommendation
ADMIT    5920
DENY     3087
Name: count, dtype: int64

In [ ]:
gender_order = ["Women", "Men", "Other", "Unknown"]
df["gender"] = pd.Categorical(df["gender"], categories=gender_order, ordered=True)

# Calculate counts and percentages by gender and recommendation
grouped = (
    df.groupby(["gender", "recommendation"])
      .size()
      .reset_index(name="count")
)

# total per gender
grouped["total_gender"] = grouped.groupby("gender")["count"].transform("sum")
grouped["percent"] = grouped["count"] / grouped["total_gender"]

color_discrete_map = {
    "ADMIT": "#1f4e79",
    "DENY": "#7f7f7f"
}

fig = px.bar(
    grouped,
    x="gender",
    y="percent",
    color="recommendation",
    barmode="stack",
    title="Admission Decision Ratio by Gender",
    color_discrete_map=color_discrete_map
)

fig.update_layout(
    template="plotly_white",
    xaxis_title="Gender",
    yaxis_title="Percentage of Applications",
    yaxis_tickformat=".0%",
    legend_title_text="Admission Decision",
    font=dict(size=14),
    bargap=0.25
)

fig.show()

/tmp/ipython-input-1463988434.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["gender", "recommendation"])
/tmp/ipython-input-1463988434.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped["total_gender"] = grouped.groupby("gender")["count"].transform("sum")

In [ ]:

gender_order = ["Women", "Men", "Other", "Unknown"]
df["gender"] = pd.Categorical(df["gender"], categories=gender_order, ordered=True)

# Filter to admitted students only
df_admit = df[df["recommendation"] == "ADMIT"].copy()

# Count admits by gender
admit_gender = (
    df_admit
    .groupby("gender", observed=True)
    .size()
    .reset_index(name="count")
)

# Compute percentage of admits by gender
total_admits = admit_gender["count"].sum()
admit_gender["percent"] = admit_gender["count"] / total_admits

color_discrete_map = {
    "Women":   "#8e4585",
    "Men":     "#003f5c",
    "Other":   "#7f7f7f",
    "Unknown": "#b0b0b0",
}

fig = px.bar(
    admit_gender,
    x="gender",
    y="percent",
    text=admit_gender["percent"].map(lambda x: f"{x:.1%}"),
    title="Brooklyn College Freshman Admits by Gender",
    color="gender",
    category_orders={"gender": gender_order},
    color_discrete_map=color_discrete_map,
)

fig.update_layout(
    template="plotly_white",
    xaxis_title="Gender",
    yaxis_title="Percentage of Admitted Students",
    yaxis_tickformat=".0%",
    showlegend=False,
    font=dict(size=16),
)

fig.update_traces(textposition="outside")

fig.show()

In [ ]:
rec = df["recommendation"].value_counts().reset_index()
rec.columns = ["recommendation", "count"]

total = rec["count"].sum()
rec["percent"] = rec["count"] / total

rec["label"] = rec.apply(
    lambda row: f"{row['count']} ({row['percent']:.1%})", axis=1
)

color_map = {
    "ADMIT": "#2A4B7C",
    "DENY": "#B0B0B0"
}

fig = px.bar(
    rec,
    x="recommendation",
    y="count",
    color="recommendation",
    text="label",
    title="Overall Admission Outcomes",
    color_discrete_map=color_map,
    hover_data={
        "count": True,
        "percent": ":.2%",
        "recommendation": False
    }
)

fig.update_traces(
    textposition="outside",
    hovertemplate="<b>%{x}</b><br>Count: %{customdata[0]}<br>Percentage: %{customdata[1]:.2%}<extra></extra>"
)

fig.update_layout(
    template="plotly_white",
    xaxis_title="Admission Decision",
    yaxis_title="Number of Applications",
    font=dict(size=14),
    showlegend=False,
    bargap=0.35
)

fig.show()

In [ ]:
# Get top 10 schools by application count
school_counts = (
    df["hs_last_attended_name"]
      .value_counts()
      .reset_index()
      .head(10)
)

school_counts.columns = ["high_school", "count"]

# Calculate percentage of total applications
total_apps = df.shape[0]
school_counts["percent"] = school_counts["count"] / total_apps

school_counts["label"] = school_counts.apply(
    lambda row: f"{row['count']} ({row['percent']:.1%})",
    axis=1
)

professional_colors = [
    "#2A4B7C",
    "#4F6D7A",
    "#6C757D",
    "#5A8F7B",
    "#8C7A9C",
    "#A67F58",
    "#7F8C8D",
    "#3C6E71",
    "#9A9EAB",
    "#556B8E"
]

fig = px.bar(
    school_counts,
    x="high_school",
    y="count",
    text="label",
    color="high_school",
    title="Top 10 High Schools by Application Count",
    color_discrete_sequence=professional_colors,
    hover_data={
        "count": True,
        "percent": ":.2%",
        "high_school": True
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    template="plotly_white",
    xaxis_title="High School Name",
    yaxis_title="Number of Applications",
    font=dict(size=13),
    bargap=0.35,
    showlegend=False
)

fig.update_xaxes(tickangle=45)

fig.show()

In [ ]:
# Calculate admit/deny counts per school
school_decisions = (
    df.groupby(["hs_last_attended_name", "recommendation"])
      .size()
      .unstack(fill_value=0)
)

for col in ["ADMIT", "DENY"]:
    if col not in school_decisions.columns:
        school_decisions[col] = 0

# Calculate total applications and acceptance rate
school_decisions["total_apps"] = school_decisions["ADMIT"] + school_decisions["DENY"]
school_decisions["accept_rate"] = school_decisions["ADMIT"] / school_decisions["total_apps"]

# Filter schools with minimum applications
min_apps = 30
filtered = school_decisions[school_decisions["total_apps"] >= min_apps].copy()

# Separate schools by acceptance rate (perfect vs. non-perfect)
perfect = filtered[filtered["accept_rate"] == 1].copy()
nonperfect = filtered[filtered["accept_rate"] < 1].copy()

# Sort perfect acceptance schools by admit count
perfect = perfect.sort_values("ADMIT", ascending=False)

# Sort non-perfect acceptance schools by acceptance rate
nonperfect = nonperfect.sort_values("accept_rate", ascending=False)

# Combine and get top 10 schools
top_schools = pd.concat([perfect, nonperfect]).head(10).reset_index()
top_schools.rename(columns={"hs_last_attended_name": "high_school"}, inplace=True)

# Define function to shorten school names
def shorten_name(name, max_len=35):
    return name if len(name) <= max_len else name[:max_len-3] + "..."

top_schools["high_school_short"] = top_schools["high_school"].apply(shorten_name)

# Create labels for bars
top_schools["label"] = top_schools.apply(
    lambda row: f"{row['accept_rate']:.1%} ({row['ADMIT']}/{int(row['total_apps'])})",
    axis=1
)

professional_colors = [
    "#2A4B7C",
    "#4F6D7A",
    "#6C757D",
    "#5A8F7B",
    "#8C7A9C",
    "#A67F58",
    "#7F8C8D",
    "#3C6E71",
    "#9A9EAB",
    "#556B8E"
]

# Plot the bar chart
fig = px.bar(
    top_schools,
    x="high_school_short",
    y="accept_rate",
    text="label",
    title="Top High Schools by Acceptance Quality",
    color="high_school_short",
    color_discrete_sequence=professional_colors,
    hover_data={
        "high_school": True,
        "accept_rate": ":.2%",
        "ADMIT": True,
        "total_apps": True,
        "high_school_short": False
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    template="plotly_white",
    xaxis_title="High School",
    yaxis_title="Acceptance Rate",
    yaxis_tickformat=".0%",
    font=dict(size=13),
    bargap=0.35,
    showlegend=False,
    xaxis_tickangle=45,
    margin=dict(b=120)
)

fig.show()

In [ ]:
# Create binary admit column
df["admit_binary"] = df["recommendation"].apply(lambda x: 1 if x == "ADMIT" else 0)

# Define GPA bins and labels
bins = [0, 70, 80, 85, 90, 95, 110]
labels = ["<70", "70–80", "80–85", "85–90", "90–95", "95–100"]

df["gpa_band"] = pd.cut(df["overall_gpa"], bins=bins, labels=labels, include_lowest=True)

# Calculate acceptance rate per GPA band
band_rates = (
    df.groupby("gpa_band")["admit_binary"]
      .mean()
      .reset_index()
)

band_rates["count"] = df.groupby("gpa_band")["admit_binary"].count().values
band_rates["label"] = band_rates.apply(
    lambda row: f"{row['admit_binary']:.1%} ({row['count']} students)",
    axis=1
)

color = "#2A4B7C"

# Plot acceptance rate by GPA band
fig = px.bar(
    band_rates,
    x="gpa_band",
    y="admit_binary",
    text="label",
    title="Admission Rate by High School GPA Band",
    color_discrete_sequence=[color],
    labels={"admit_binary": "Acceptance Rate", "gpa_band": "GPA Band"}
)

fig.update_traces(textposition="outside")

fig.update_layout(
    template="plotly_white",
    yaxis_tickformat=".0%",
    xaxis_title="High School GPA Band",
    yaxis_title="Acceptance Rate",
    font=dict(size=14),
    bargap=0.3,
    showlegend=False
)

fig.show()

/tmp/ipython-input-1128948294.py:17: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/tmp/ipython-input-1128948294.py:22: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
# Create binary admit column
df["admit_binary"] = (df["recommendation"] == "ADMIT").astype(int)

# Define GPA bins and labels
bins = [0, 70, 80, 85, 90, 95, 110]
labels = ["Below 70", "70–80", "80–85", "85–90", "90–95", "95–100"]

df["gpa_band"] = pd.cut(
    df["overall_gpa"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

# Calculate admit count, total students, and acceptance rate per GPA band
band_rates = (
    df.groupby("gpa_band", observed=True)
      .agg(
          admit_count=("admit_binary", "sum"),
          total_students=("admit_binary", "count")
      )
      .reset_index()
)

band_rates["acceptance_rate"] = (
    band_rates["admit_count"] / band_rates["total_students"]
)

# Create labels for bars
band_rates["rate_label"] = band_rates["acceptance_rate"].map(lambda x: f"{x:.1%}")

band_color_map = {
    "Below 70": "#b71c1c",
    "70–80":    "#e65100",
    "80–85":    "#f9a825",
    "85–90":    "#7cb342",
    "90–95":    "#2e7d32",
    "95–100":   "#1b5e20"
}
bar_colors = band_rates["gpa_band"].astype(str).map(band_color_map).tolist()

# Create bar chart
fig = px.bar(
    band_rates,
    x="gpa_band",
    y="acceptance_rate",
    text="rate_label",
    title="Freshman Admission Rates by High School GPA Range",
    labels={
        "gpa_band": "High School GPA Range",
        "acceptance_rate": "Chance of Admission"
    },
    category_orders={"gpa_band": labels}
)

fig.update_traces(
    marker_color=bar_colors,
    textposition="outside",
    customdata=band_rates[["admit_count", "total_students"]].to_numpy(),
    hovertemplate=(
        "<b>%{x}</b><br>" +
        "Chance of admission: %{y:.1%}<br>" +
        "Admitted: %{customdata[0]} of %{customdata[1]} students" +
        "<extra></extra>"
    )
)

# Update layout
fig.update_layout(
    template="plotly_white",
    yaxis_tickformat=".0%",
    xaxis_title="High School GPA Range",
    yaxis_title="Chance of Admission",
    font=dict(size=15),
    bargap=0.35,
    showlegend=False
)

fig.show()

In [ ]:
# Create binary admit target
df["admit_binary"] = df["recommendation"].apply(lambda x: 1 if x == "ADMIT" else 0)

def plot_logistic_for_grade(df, grade_col, target_col="admit_binary"):
    """
    Fit and plot a logistic regression model for one grade column.
    grade_col: name of the GPA column (e.g., 'overall_gpa', 'math_gpa')
    """
    # Drop rows with missing values
    data = df.dropna(subset=[grade_col, target_col]).copy()

    X = data[[grade_col]].values
    y = data[target_col].values

    # Scale feature
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Fit logistic regression model
    model = LogisticRegression()
    model.fit(X_scaled, y)

    # Generate GPA range for prediction curve
    gpa_min, gpa_max = data[grade_col].min(), data[grade_col].max()
    gpa_range = np.linspace(gpa_min, gpa_max, 300).reshape(-1, 1)
    gpa_range_scaled = scaler.transform(gpa_range)
    probs = model.predict_proba(gpa_range_scaled)[:, 1]

    # Create DataFrame for the curve
    curve_df = pd.DataFrame({
        grade_col: gpa_range.flatten(),
        "prob_admit": probs
    })

    # Calculate GPA cutoff for 50% admission probability
    z_cutoff = -model.intercept_[0] / model.coef_[0][0]
    gpa_cutoff = scaler.inverse_transform([[z_cutoff]])[0][0]

    # Plot admission probability curve
    fig = px.line(
        curve_df,
        x=grade_col,
        y="prob_admit",
        title=f"Logistic Regression: Probability of Admission vs {grade_col}",
        labels={grade_col: grade_col.replace("_", " ").title(),
                "prob_admit": "Admission Probability"},
        color_discrete_sequence=["#2A4B7C"]
    )

    # Add raw student outcome data points
    fig.add_scatter(
        x=data[grade_col],
        y=data[target_col],
        mode="markers",
        opacity=0.25,
        marker=dict(color="#6C757D"),
        name="Student outcomes (0 = Deny, 1 = Admit)"
    )

    # Add 50% probability cutoff line
    fig.add_vline(
        x=gpa_cutoff,
        line_dash="dash",
        line_color="#B56576",
        annotation_text=f"50% cutoff ≈ {gpa_cutoff:.1f}",
        annotation_position="top left"
    )

    fig.update_layout(
        template="plotly_white",
        yaxis_range=[-0.05, 1.05],
        yaxis_tickformat=".0%",
        font=dict(size=14)
    )

    fig.show()
    print(f"{grade_col}: estimated GPA for 50% admit probability ≈ {gpa_cutoff:.2f}")

# Run logistic regression for each GPA column
grade_cols = ["overall_gpa", "english_gpa", "math_gpa", "science_gpa", "social_studies_gpa"]

for col in grade_cols:
    plot_logistic_for_grade(df, col)

overall_gpa: estimated GPA for 50% admit probability ≈ 85.06

english_gpa: estimated GPA for 50% admit probability ≈ 84.38

math_gpa: estimated GPA for 50% admit probability ≈ 81.84

science_gpa: estimated GPA for 50% admit probability ≈ 83.10

social_studies_gpa: estimated GPA for 50% admit probability ≈ 84.04

In [ ]:
df.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa,intended_major,admit_binary,gpa_band
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67,Art BA,1,95–100
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17,Biology BS,1,95–100
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38,Art BA,1,95–100
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50,Business Administration BBA,1,95–100
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00,Undeclared Major,1,90–95

In [ ]:
# Create binary admit column
df["admit_binary"] = df["recommendation"].apply(lambda x: 1 if x == "ADMIT" else 0)

# Calculate acceptance rate and count per ethnicity
eth = (
    df.groupby("ethnicity")["admit_binary"]
      .agg(["mean", "count"])
      .reset_index()
)

eth.rename(columns={"mean": "accept_rate"}, inplace=True)

# Create labels for bars
eth["label"] = eth.apply(
    lambda row: f"{row['accept_rate']:.1%} ({row['count']} students)",
    axis=1
)

# Sort by acceptance rate
eth = eth.sort_values("accept_rate", ascending=False)

color = "#2A4B7C"

# Plot admission rate by ethnicity
fig = px.bar(
    eth,
    x="ethnicity",
    y="accept_rate",
    text="label",
    title="Admission Rate by Ethnicity",
    color_discrete_sequence=[color],
    hover_data={
        "ethnicity": True,
        "accept_rate": ":.2%",
        "count": True
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    template="plotly_white",
    yaxis_tickformat=".0%",
    xaxis_title="Ethnicity",
    yaxis_title="Acceptance Rate",
    font=dict(size=14),
    bargap=0.3,
    showlegend=False,
    xaxis_tickangle=45,
    margin=dict(b=120)
)

fig.show()

In [ ]:
# Count applicants per ethnicity
eth_counts = (
    df["ethnicity"]
      .value_counts()
      .reset_index()
)

eth_counts.columns = ["ethnicity", "count"]

# Calculate percentage of total applicants
total_apps = eth_counts["count"].sum()
eth_counts["percent"] = eth_counts["count"] / total_apps

# Create labels for bars
eth_counts["label"] = eth_counts.apply(
    lambda row: f"{row['count']} ({row['percent']:.1%})",
    axis=1
)

# Sort by count
eth_counts = eth_counts.sort_values("count", ascending=False)

professional_colors = [
    "#2A4B7C",
    "#4F6D7A",
    "#6C757D",
    "#5A8F7B",
    "#8C7A9C",
    "#A67F58",
    "#7F8C8D",
    "#3C6E71",
    "#9A9EAB",
    "#556B8E"
]

fig = px.bar(
    eth_counts,
    x="ethnicity",
    y="count",
    text="label",
    title="Distribution of Applicants by Ethnicity",
    color="ethnicity",
    color_discrete_sequence=professional_colors,
    hover_data={
        "count": True,
        "percent": ":.2%",
        "ethnicity": True
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    template="plotly_white",
    xaxis_title="Ethnicity",
    yaxis_title="Number of Applicants",
    font=dict(size=14),
    bargap=0.3,
    showlegend=False,
    xaxis_tickangle=45,
    margin=dict(b=120)
)

fig.show()

In [ ]:
# Filter for admitted students
df_admit = df[df["recommendation"] == "ADMIT"].copy()

# Count admitted students per ethnicity
eth_admit = (
    df_admit["ethnicity"]
        .value_counts()
        .reset_index()
)

eth_admit.columns = ["ethnicity", "count"]

# Calculate percentage of all admitted students
total_admits = eth_admit["count"].sum()
eth_admit["percent"] = eth_admit["count"] / total_admits

# Create labels for bars
eth_admit["label"] = eth_admit.apply(
    lambda row: f"{row['count']} ({row['percent']:.1%})",
    axis=1
)

# Sort by count
eth_admit = eth_admit.sort_values("count", ascending=False)

professional_colors = [
    "#2A4B7C",
    "#4F6D7A",
    "#6C757D",
    "#5A8F7B",
    "#8C7A9C",
    "#A67F58",
    "#7F8C8D",
    "#3C6E71",
    "#9A9EAB",
    "#556B8E"
]

fig = px.bar(
    eth_admit,
    x="ethnicity",
    y="count",
    text="label",
    title="Distribution of Admitted Students by Ethnicity",
    color="ethnicity",
    color_discrete_sequence=professional_colors,
    hover_data={
        "count": True,
        "percent": ":.2%",
        "ethnicity": True
    }
)

fig.update_traces(textposition="outside")

fig.update_layout(
    template="plotly_white",
    xaxis_title="Ethnicity",
    yaxis_title="Number of Admitted Students",
    font=dict(size=14),
    bargap=0.3,
    showlegend=False,
    xaxis_tickangle=45,
    margin=dict(b=120)
)

fig.show()

In [ ]:
# Count applicants per ethnicity
eth_counts = (
    df["ethnicity"]
      .value_counts()
      .reset_index()
)

eth_counts.columns = ["ethnicity", "count"]

# Calculate percentage of total applicants
total_apps = eth_counts["count"].sum()
eth_counts["percent"] = eth_counts["count"] / total_apps

# Create hover labels
eth_counts["hover_label"] = eth_counts.apply(
    lambda row: f"{row['ethnicity']}<br>{row['count']} applicants<br>{row['percent']:.1%} of total",
    axis=1
)

professional_colors = [
    "#2A4B7C",
    "#4F6D7A",
    "#6C757D",
    "#5A8F7B",
    "#8C7A9C",
    "#A67F58",
    "#7F8C8D",
    "#3C6E71",
    "#9A9EAB",
    "#556B8E"
]

fig = px.pie(
    eth_counts,
    names="ethnicity",
    values="count",
    title="Distribution of Applicants by Ethnicity",
    color="ethnicity",
    color_discrete_sequence=professional_colors,
    hole=0.3
)

fig.update_traces(
    textposition="inside",
    texttemplate="%{percent:.1%}",
    hovertemplate="<b>%{label}</b><br>%{percent:.1%}<br>%{value} students<extra></extra>",
)

fig.update_layout(
    template="plotly_white",
    showlegend=True,
    legend_title_text="Ethnicity",
    font=dict(size=14)
)

fig.show()

In [ ]:
df.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa,intended_major,admit_binary,gpa_band
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67,Art BA,1,95–100
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17,Biology BS,1,95–100
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38,Art BA,1,95–100
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50,Business Administration BBA,1,95–100
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00,Undeclared Major,1,90–95

In [ ]:
cols_to_drop = ['intended_major', 'admit_binary', 'gpa_band']
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

In [ ]:
# Count applicants per ethnicity
eth_total = (
    df.groupby("ethnicity")
      .size()
      .reset_index(name="applicants")
)

# Count admitted students per ethnicity
eth_admit = (
    df[df["recommendation"] == "ADMIT"]
      .groupby("ethnicity")
      .size()
      .reset_index(name="admitted")
)

# Merge data and calculate admission rate
eth_merged = pd.merge(eth_total, eth_admit, on="ethnicity", how="left").fillna(0)
eth_merged["admitted"] = eth_merged["admitted"].astype(int)

eth_merged["admit_rate"] = eth_merged["admitted"] / eth_merged["applicants"]

# Sort by number of applicants
eth_merged = eth_merged.sort_values("applicants", ascending=False)
eth_order = eth_merged["ethnicity"].tolist()

# Reshape data for grouped bar chart
plot_df = eth_merged.melt(
    id_vars=["ethnicity", "admit_rate"],
    value_vars=["applicants", "admitted"],
    var_name="status",
    value_name="count"
)

status_label_map = {
    "applicants": "Applicants",
    "admitted": "Admitted"
}
plot_df["status"] = plot_df["status"].map(status_label_map)

# Define color map
color_map = {
    "Applicants": "#2A4B7C",
    "Admitted":   "#2E7D32"
}

# Create grouped bar chart
fig = px.bar(
    plot_df,
    x="ethnicity",
    y="count",
    color="status",
    barmode="group",
    text="count",
    title="Applicants and Admitted Students by Ethnicity",
    category_orders={"ethnicity": eth_order, "status": ["Applicants", "Admitted"]},
    color_discrete_map=color_map,
    labels={
        "ethnicity": "Ethnicity",
        "count": "Number of Students",
        "status": ""
    }
)

# Update traces with custom hover info
fig.update_traces(
    textposition="outside",
    customdata=plot_df[["admit_rate"]].to_numpy(),
    hovertemplate=(
        "<b>%{x}</b><br>" +
        "Decision: %{legendgroup}<br>" +
        "Share of this ethnicity: %{y} <br>" +
        "Admit rate in this group: %{customdata[0]:.1%}" +
        "<extra></extra>"
    )
)

# Update layout
fig.update_layout(
    template="plotly_white",
    xaxis_title="Ethnicity",
    yaxis_title="Number of Students",
    font=dict(size=14),
    bargap=0.25,
    bargroupgap=0.12,
    xaxis_tickangle=35,
    margin=dict(b=110),
    legend_title_text=""
)

fig.show()

In [ ]:
# Order ethnicities by applicant count
ethnicity_order = (
    df["ethnicity"]
      .value_counts()
      .index
      .tolist()
)

df["ethnicity"] = pd.Categorical(df["ethnicity"],
                                 categories=ethnicity_order,
                                 ordered=True)

# Calculate counts and percentages by ethnicity and recommendation
grouped_eth = (
    df.groupby(["ethnicity", "recommendation"], observed=True)
      .size()
      .reset_index(name="count")
)

grouped_eth["total_ethnicity"] = grouped_eth.groupby("ethnicity")["count"].transform("sum")
grouped_eth["percent"] = grouped_eth["count"] / grouped_eth["total_ethnicity"]

color_discrete_map = {
    "ADMIT": "#1f4e79",
    "DENY":  "#7f7f7f"
}

# Plot stacked bar chart
fig = px.bar(
    grouped_eth,
    x="ethnicity",
    y="percent",
    color="recommendation",
    barmode="stack",
    title="Admission Decision Ratio by Ethnicity",
    color_discrete_map=color_discrete_map,
    category_orders={"ethnicity": ethnicity_order}
)

# Update layout and hover info
fig.update_layout(
    template="plotly_white",
    xaxis_title="Ethnicity",
    yaxis_title="Percentage of Applications",
    yaxis_tickformat=".0%",
    legend_title_text="Admission Decision",
    font=dict(size=14),
    bargap=0.25,
    xaxis_tickangle=35,
    margin=dict(b=110)
)

fig.update_traces(
    hovertemplate=(
        "<b>%{x}</b><br>" +
        "Decision: %{legendgroup}<br>" +
        "Share of this ethnicity: %{y:.1%}<br>" +
        "Applications: %{customdata[0]} of %{customdata[1]}" +
        "<extra></extra>"
    ),
    customdata=grouped_eth[["count", "total_ethnicity"]].to_numpy()
)

fig.show()

/tmp/ipython-input-2126921394.py:26: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
# Count gender distribution
gender_counts = (
    df["gender"]
      .value_counts()
      .reset_index()
)

gender_counts.columns = ["gender", "count"]

# Calculate percentages
total = gender_counts["count"].sum()
gender_counts["percent"] = gender_counts["count"] / total

# Order genders
gender_order = ["Women", "Men", "Other", "Unknown"]
gender_counts["gender"] = pd.Categorical(gender_counts["gender"], categories=gender_order, ordered=True)
gender_counts = gender_counts.sort_values("gender")

color_map = {
    "Women": "#8C86F6",
    "Men":   "#5AD1C7",
    "Other": "#9FA6B2",
    "Unknown": "#D1D5DB"
}

# Create donut chart
fig = px.pie(
    gender_counts,
    names="gender",
    values="percent",
    color="gender",
    color_discrete_map=color_map,
    hole=0.65
)

fig.update_traces(
    textinfo="percent",
    texttemplate="%{percent:.1%}",
    hovertemplate="<b>%{label}</b><br>%{percent:.1%}<br>%{value} students<extra></extra>",
)

# Update layout
fig.update_layout(
    title="Gender Split",
    title_x=0.5,
    font=dict(size=16),
    showlegend=True,
    legend_title_text="",
    margin=dict(t=80, b=40, l=40, r=40),
    template="plotly_white"
)

fig.show()

In [ ]:
# Count applicants per ethnicity
eth_total = (
    df.groupby("ethnicity")
      .size()
      .reset_index(name="applicants")
)

# Convert ethnicity to string type
eth_total["ethnicity"] = eth_total["ethnicity"].astype(str)

# Count admitted students per ethnicity
eth_admit = (
    df[df["recommendation"] == "ADMIT"]
      .groupby("ethnicity")
      .size()
      .reset_index(name="admitted")
)

# Convert ethnicity to string type
eth_admit["ethnicity"] = eth_admit["ethnicity"].astype(str)

# Merge data and calculate denial/acceptance rates
eth = pd.merge(eth_total, eth_admit, on="ethnicity", how="left").fillna(0)
eth["admitted"] = eth["admitted"].astype(int)
eth["denied"] = eth["applicants"] - eth["admitted"]
eth["accept_rate"] = eth["admitted"] / eth["applicants"]

# Calculate percentage of all applicants per ethnicity
total_apps = eth["applicants"].sum()
eth["pct_all"] = eth["applicants"] / total_apps

# Calculate within-group admit/deny percentages
eth["pct_admit_within"] = eth["admitted"] / eth["applicants"]
eth["pct_deny_within"]  = eth["denied"] / eth["applicants"]

# Calculate scaled heights for stacked bars
eth["height_admit"] = eth["pct_all"] * eth["pct_admit_within"]
eth["height_deny"]  = eth["pct_all"] * eth["pct_deny_within"]

# Prepare data for stacked bar chart
long_df = eth.melt(
    id_vars=["ethnicity", "pct_all", "accept_rate", "admitted", "denied", "applicants"],
    value_vars=["height_admit", "height_deny"],
    var_name="decision",
    value_name="height"
)

decision_map = {
    "height_admit": "Admitted",
    "height_deny":  "Denied"
}
long_df["decision"] = long_df["decision"].map(decision_map)

# Define color map
color_map = {
    "Admitted": "#1f4e79",
    "Denied":   "#7f7f7f"
}

# Create stacked bar chart
fig = px.bar(
    long_df,
    x="ethnicity",
    y="height",
    color="decision",
    barmode="stack",
    title="Ethnicity Representation and Admission Split",
    color_discrete_map=color_map,
)

# Update layout
fig.update_layout(
    template="plotly_white",
    yaxis_title="Share of Total Applicants",
    xaxis_title="Ethnicity",
    yaxis_tickformat=".0%",
    font=dict(size=14),
    xaxis_tickangle=35,
    bargap=0.25,
    margin=dict(b=130),
    legend_title_text=""
)

# Update traces with custom hover info
fig.update_traces(
    customdata=long_df[["applicants", "admitted", "denied", "accept_rate"]].to_numpy(),
    hovertemplate=(
        "<b>%{x}</b><br>" +
        "Decision: %{legendgroup}<br>" +
        "Share of total applicants: %{y:.1%}<br>" +
        "<br>" +
        "Total applicants: %{customdata[0]}<br>" +
        "Admitted: %{customdata[1]}<br>" +
        "Denied: %{customdata[2]}<br>" +
        "Acceptance rate: %{customdata[3]:.1%}" +
        "<extra></extra>"
    )
)

fig.show()

/tmp/ipython-input-1526876724.py:8: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/tmp/ipython-input-1526876724.py:19: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

# 12/13/2025

In [ ]:
df.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00

In [ ]:
df["recommendation"].value_counts()

recommendation
ADMIT    5920
DENY     3087
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9007 entries, 0 to 9006
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   evaluation_code        9007 non-null   object
 1   recommendation         9007 non-null   object
 2   gender                 9007 non-null   category
 3   ethnicity              9007 non-null   category
 4   hs_last_attended_name  9007 non-null   object
 5   overall_gpa            9007 non-null   float64
 6   english_gpa            9007 non-null   float64
 7   math_gpa               9007 non-null   float64
 8   science_gpa            9007 non-null   float64
 9   social_studies_gpa     9007 non-null   float64
dtypes: category(2), float64(5), object(3)
memory usage: 581.2+ KB

In [ ]:
df.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa,neighborhood
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67,Sunset Park
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17,Sunset Park
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38,Southern Brooklyn
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50,Southwest Brooklyn
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00,Southern Brooklyn

In [ ]:
df["neighborhood"].value_counts()

neighborhood
Southern Brooklyn                  1180
Borough Park                       1080
Flatbush                            997
Canarsie and Flatlands              793
Southwest Brooklyn                  741
Not NYC                             529
Central Brooklyn                    528
Sunset Park                         399
East New York and New Lots          307
Bushwick and Williamsburg           262
Northwest Brooklyn                  233
Southwest Queens                    175
West Queens                         145
Rockaways                           135
South Shore                         123
West Central Queens                 120
Stapleton and St. George            120
Jamaica                             111
Lower East Side                      72
Northwest Queens                     71
Southeast Queens                     69
Inwood and Washington Heights        66
Port Richmond                        59
Willowbrook                          55
Southeast Bronx                      54
Greenpoint                           53
High Bridge and Morrisania           49
Central Harlem                       48
North Queens                         44
East Harlem                          42
Hunts Point and Mott Haven           39
Central Bronx                        38
Bronx Park and Fordham               38
Upper West Side                      36
Chelsea and Clinton                  34
Northeast Bronx                      32
Upper East Side                      29
Gramercy Park and Murray Hill        19
Greenwich Village and Soho           19
Northeast Queens                     15
Lower Manhattan                      14
Kingsbridge and Riverdale            12
Unknown                              11
Central Queens                       10
Downtown - Heights - Park Slope       1
Name: count, dtype: int64

In [ ]:
df.isna().sum()

evaluation_code          0
recommendation           0
gender                   0
ethnicity                0
hs_last_attended_name    0
overall_gpa              0
english_gpa              0
math_gpa                 0
science_gpa              0
social_studies_gpa       0
neighborhood             0
dtype: int64

In [ ]:
df.isna().sum()

evaluation_code          0
recommendation           0
gender                   0
ethnicity                0
hs_last_attended_name    0
overall_gpa              0
english_gpa              0
math_gpa                 0
science_gpa              0
social_studies_gpa       0
neighborhood             0
zip_code                 0
dtype: int64

In [ ]:
df["zip_code"].value_counts()

zip_code
10029    72
11420    70
10006    70
11226    66
11104    66
         ..
10012    39
10452    39
11432    39
11691    39
10035    38
Name: count, Length: 178, dtype: int64

In [ ]:
df.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa,neighborhood,zip_code
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67,Sunset Park,10308
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17,Sunset Park,10029
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38,Southern Brooklyn,10464
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50,Southwest Brooklyn,10011
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00,Southern Brooklyn,11426

In [ ]:
df.drop(columns=["neighborhood", "zip_code"], inplace=True, errors="ignore")

In [ ]:
df.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00

In [ ]:
df_zip = pd.read_csv("bc_students_by_zip.csv")

In [ ]:
df_zip.head()

   zip_code  student_count nyc_area
0     14127              1  Not NYC
1     14075              1  Not NYC
2     14221              1  Not NYC
3     14621              1  Not NYC
4     14534              1  Not NYC

In [ ]:
df_zip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 604 entries, 0 to 603
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   zip_code       604 non-null    int64
 1   student_count  604 non-null    int64
 2   nyc_area       604 non-null    object
dtypes: int64(2), object(1)
memory usage: 14.3+ KB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9007 entries, 0 to 9006
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   evaluation_code        9007 non-null   object
 1   recommendation         9007 non-null   object
 2   gender                 9007 non-null   category
 3   ethnicity              9007 non-null   category
 4   hs_last_attended_name  9007 non-null   object
 5   overall_gpa            9007 non-null   float64
 6   english_gpa            9007 non-null   float64
 7   math_gpa               9007 non-null   float64
 8   science_gpa            9007 non-null   float64
 9   social_studies_gpa     9007 non-null   float64
dtypes: category(2), float64(5), object(3)
memory usage: 581.2+ KB

In [ ]:
df_zip["nyc_area"].value_counts()

nyc_area
Not NYC          426
Queens            57
Manhattan         46
Brooklyn          38
Bronx             25
Staten Island     12
Name: count, dtype: int64

In [ ]:
# Ensure ZIP code types match
df["zip_code"] = df["zip_code"].astype(str)
df_zip["zip_code"] = df_zip["zip_code"].astype(str)

# Create ZIP code to NYC area lookup
zip_to_area = df_zip.set_index("zip_code")["nyc_area"].to_dict()

# Assign NYC area to DataFrame
df["nyc_area"] = df["zip_code"].map(zip_to_area).fillna("Not NYC")

df["nyc_area"].value_counts()

nyc_area
Brooklyn         5488
Queens           1542
Not NYC          1134
Manhattan         328
Staten Island     301
Bronx             214
Name: count, dtype: int64

In [ ]:
df.head()

,evaluation_code,recommendation,gender,ethnicity,hs_last_attended_name,overall_gpa,english_gpa,math_gpa,science_gpa,social_studies_gpa,zip_code,nyc_area
0,FRSHREG,ADMIT,Men,White,New Explorations Science Technology Math,97.30,96.67,97.00,96.00,95.67,11228,Brooklyn
1,FRSHREG,ADMIT,Women,Asian,Young Womens Leadership School Queens,96.93,96.00,97.25,95.33,96.17,11219,Brooklyn
2,FRSHREG,ADMIT,Women,Hispanic/Latino,Brooklyn Technical HS,97.56,98.17,96.30,96.83,97.38,11210,Brooklyn
3,FRSHREG,ADMIT,Women,Two or more races,Bronx HS of Science,97.87,99.00,97.25,97.36,96.50,11210,Brooklyn
4,FRSHREG,ADMIT,Men,Hispanic/Latino,Urban Action Academy,93.49,92.25,92.71,94.50,92.00,11229,Brooklyn

In [ ]:
df.isna().sum()

evaluation_code          0
recommendation           0
gender                   0
ethnicity                0
hs_last_attended_name    0
overall_gpa              0
english_gpa              0
math_gpa                 0
science_gpa              0
social_studies_gpa       0
zip_code                 0
nyc_area                 0
dtype: int64

In [ ]:
gpa_cols = ["overall_gpa","english_gpa","math_gpa","science_gpa","social_studies_gpa"]
df[gpa_cols].dtypes

overall_gpa           float64
english_gpa           float64
math_gpa              float64
science_gpa           float64
social_studies_gpa    float64
dtype: object

In [ ]:
df["zip_code"] = df["zip_code"].astype(str).str.zfill(5)

In [ ]:
df["nyc_area"].value_counts()

nyc_area
Brooklyn         5488
Queens           1542
Not NYC          1134
Manhattan         328
Staten Island     301
Bronx             214
Name: count, dtype: int64

In [ ]:
df.to_csv("fall_2025_freshman_applicants_cleaned.csv", index=False)